<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <?php
        $this->headLink()
             ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css')
             ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootswatch/3.1.1/yeti/bootstrap.min.css');
        ?>
        
        <?php
            echo $this->headLink();
        ?>
    </head>
    <body>
        <div class="container" style="margin-top: 10%;"> <!-- CONTENT -->
            <?php echo $this->partial('smx-google-auth/flashmessenger'); ?>
            <?php echo $this->content; ?>
        </div>
        
        <?php 
            $this->headScript()
                 ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js')
                 ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js')
                 ->prependFile('//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
                 ->prependFile('//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'));

            echo $this->headScript();
            echo $this->inlineScript();
        ?>
    </body>
</html>
